#pragma once
#include <SFML/Graphics.hpp>
#include <vector>

const int MAP_WIDTH = 26;
const int MAP_HIGHT = 26;
sf::String firstLevelMap[MAP_HIGHT] =
{
	"                          ",
	"                          ",
	"  ##  ##  ##  ##  ##  ##  ",
	"  ##  ##  ##  ##  ##  ##  ",
	"  ##  ##  ##  ##  ##  ##  ",
	"  ##  ##  ##  ##  ##  ##  ",
	"  ##  ##  ##  ##  ##  ##  ",
	"  ##  ##  ##  ##  ##  ##  ",
	"  ##  ##  ##  ##  ##  ##  ",
	"  ##  ##          ##  ##  ",
	"  ##  ##          ##  ##  ",
	"          ##  ##          ",
	"          ##  ##          ",
	"##  ####          ####  ##",
	"ww  ####          ####  ww",
	"          ##  ##          ",
	"          ######          ",
	"  ##  ##  ######  ##  ##  ",
	"  ##  ##  ##  ##  ##  ##  ",
	"  ##  ##  ##  ##  ##  ##  ",
	"  ##  ##  ##  ##  ##  ##  ",
	"  ##  ##          ##  ##  ",
	"  ##  ##          ##  ##  ",
	"  ##  ##   ####   ##  ##  ",
	"           #qo#           ",
	"           #er#           ",
};

sf::String secondLevelMap[MAP_HIGHT] =
{
	"      ww      ww          ",
	"      ww      ww          ",
	"  ##  ww      ##  ##  ##  ",
	"  ##  ww      ##  ##  ##  ",
	"  ##        ####  ##ww##  ",
	"  ##        ####  ##ww##  ",
	"      ##          ww      ",
	"      ##          ww      ",
	"kk    ##    ww    ##kk##ww",
	"kk    ##    ww    ##kk##ww",
	"kkkk      ##    ww  kk    ",
	"kkkk      ##    ww  kk    ",
	"  ######kkkkkkww    kk##  ",
	"  ######kkkkkkww    kk##  ",
	"      wwkk##  ##  ##  ##  ",
	"      wwkk##  ##  ##  ##  ",
	"ww##  ww  ##  ##      ##  ",
	"ww##  ww  ##  ##      ##  ",
	"  ##  ##  ######  ##ww##  ",
	"  ##  ##  ######  ##ww##  ",
	"  ##  ##  ######          ",
	"  ##  ##  ######          ",
	"  ##              ##  ##  ",
	"  ##       ####   ##  ##  ",
	"  ##  ##   #qo#   ######  ",
	"  ##  ##   #er#   ######  ",
};

sf::String thirdLevelMap[MAP_HIGHT] =
{
	"              wwww        ",
	"                          ",
	"    wwwwwwww        ww    ",
	"    ww              ww    ",
	"    ww      kk  wwwwww    ",
	"    ww      kk    wwww    ",
	"  ww      kkww      ww    ",
	"  ww      kkww      ww    ",
	"        kkwwww      wwww  ",
	"        kkwwww        ww  ",
	"  ww  kkwwwwww  ww        ",
	"  ww  kkwwwwww  ww        ",
	"   w  wwww      wwww      ",
	"   w  wwww      wwww      ",
	"w       ww  wwwwww     w  ",
	"w       ww  wwwwww     w  ",
	"   www      wwwwkk    ww  ",
	"   www      wwwwkk    ww  ",
	"  ww        wwkk    wwww  ",
	"  ww        wwkk    wwww  ",
	"  wwwwww    kk    ww      ",
	"      ww    kk    ww      ",
	"                  ww    ww",
	"           ####       wwww",
	"           #qo#           ",
	"wwww       #er#           ",
};

sf::String fourthLevelMap[MAP_HIGHT] =
{
	"                          ",
	"      ######    ##        ",
	"    ################      ",
	"  ##################      ",
	"  kkkkkkkkkkkkkkkk####    ",
	"  kkkkkkkkkkkkkkkk####    ",
	"kkkk            kkkk####  ",
	"kkkk            kkkk####  ",
	"kk  ww    ww      kkkkkk  ",
	"kk  ww    ww      kkkkkk  ",
	"kk  ww    ww      kkkkkk  ",
	"kk  ww    ww      kkkkkk  ",
	"kk    kk        kkkk##### ",
	"kk    kk        kkkk##### ",
	"kkkkkkkkkkkkkkkkkk####### ",
	"kkkkkkkkkkkkkkkkkk####### ",
	"##kkkk####kkkkkk########  ",
	"##kkkk####kkkkkk########  ",
	"  ####################  ww",
	"  ####################  ww",
	"ww  ##ww#############   ww",
	"ww  ##ww#############   ww",
	"  ww####ww      ####wwwwww",
	"  ww##  ww #### ####wwwwww",
	"           #qo#           ",
	"           #er#           ",
};

sf::String fifthLevelMap[MAP_HIGHT] =
{
	"  ##  ##  ##  ##  ##  ##  ",
	"  ##  ##  ##  ##  ##  ##  ",
	"  ##  ##  ##  ##  ##  ##  ",
	"  ##  ##  ##  ##  ##  ##  ",
	"  ww  ww  ww  ww  ww  ww  ",
	"                          ",
	"        ##      ##        ",
	"##  ##  ##      ##  ##  ##",
	"##  ######  ##  ######  ##",
	"##  ##  ##  ##  ##  ##  ##",
	"ww  ww  ww  ww  ww  ww  ww",
	"        ww      ww        ",
	"kkkk    ##  kk  ##    kkkk",
	"kkkk    ##  kk  ##    kkkk",
	"kkkkkkkk####kk####kkkkkkkk",
	"kkkkkkkk##  kk  ##kkkkkkkk",
	"kkkkkkkkkkkkkkkkkkkkkkkkkk",
	"kkkkkkkkkkkkkkkkkkkkkkkkkk",
	"        ##kkkkkk##        ",
	"##  ##  ##kkkkkk##  ##  ##",
	"  ##  ##    kk    ##  ##  ",
	"  ##  ##    kk    ##  ##  ",
	"  ##  ##          ##  ##  ",
	"  ##  ##   ####   ##  ##  ",
	"  ##  ##   #qo#   ##  ##  ",
	"           #er#           ",
};

std::vector<sf::String* > mapsArr{ firstLevelMap, secondLevelMap, thirdLevelMap, fourthLevelMap, fifthLevelMap };
